#!/bin/bash
set -euo pipefail

# Get yunohost helpers
source /usr/share/yunohost/helpers

# remote size in bytes
declare -r REMOTE_SIZE=2199023255552
# rclone remote name (without ":")
declare -r RCLONE_REMOTE="pcloud-crypt"
# set verbosity (true|false)
declare -r VERBOSE=true
# log file
declare -r LOGFILE="/var/log/yunohost/backup-rclone.log"
# Send mail to admins group
declare -r MAIL="admins"

# Params sent by yunohost backup script
declare -r BACKUP_TMP_REP="$2"
declare -r BACKUP_NAME="$3"
declare -r LOCAL_REPO="$4"
declare -r BACKUP_SIZE="$5"
declare -r BACKUP_DESCRIPTION="$6"

declare -r INFO_FILE="${BACKUP_NAME}.info.json"
declare -r ARCHIVE_FILE="${BACKUP_NAME}.tar.gz"
declare -r LOCAL_INFO_FILE="${LOCAL_REPO}/${INFO_FILE}"
declare -r LOCAL_ARCHIVE_FILE="${LOCAL_REPO}/${ARCHIVE_FILE}"

declare -r RCLONE_DEST="${RCLONE_REMOTE}:${LOCAL_REPO}/"

# Archive size file after creation
archiveSize=0

# Message function
# $1 : message to print
# $2 : message type success|error|warning|verbose|info|<null>
msg() {
    local msg="$1"
    local type="${2-info}"
    local prefix=''
    local now=''

    case "${type}" in
        'success')
            prefix="[OK] "
            ynh_print_info --message="[OK] $msg"
            ;;
        'error')
            prefix="[ERROR] "
            ynh_print_err --message="$msg"
        ;;
        'warning')
            prefix="[WARN] "
            ynh_print_warn --message="$msg"
        ;;
        'verbose')
            if [[ $VERBOSE = false ]]; then
                return
            fi
        ;;
        'info')
            ynh_print_info --message="$msg"
        ;;
        *)
            ynh_print_err --message="[ERROR] msg type '${type}' unknown"
            exit 1
        ;;
    esac

    now="$(date "+%Y-%m-%d %H:%M:%S") "
    printf '%s%s%s\n' "$now" "$prefix" "$msg" >> "$LOGFILE"
}

# Function to tell to abord script
# Allows to send a message to mail before exit
# $1 : abording message
abord() {
    local msg="$1"

    if [[ -n $MAIL ]]; then
        echo "$msg" | mail -s "Yunohost backup rclone - ERROR" $MAIL
    fi

    msg "$msg" "error"

    exit 1
}

# Create archive file as yunohost expect
# Set global archiveSize var
function createLocalArchive() {
    # Check if there is enough space locally to create archive file
    local _availableSpaceOnDisk=$(getAvalaibleDiskSpace "${LOCAL_REPO}")
    if [[ $_availableSpaceOnDisk -lt $BACKUP_SIZE ]]; then
        abord "There is no space left on local disk to create archive (tmp size = ${BACKUP_SIZE} bytes, space left = ${_availableSpaceOnDisk} bytes"
    fi

    cd "$BACKUP_TMP_REP"
    msg "Creating info file '${LOCAL_INFO_FILE}'..."
    if [[ ! -f ${LOCAL_INFO_FILE} ]]; then
        cp info.json "${LOCAL_INFO_FILE}"
        msg "Info file '${LOCAL_INFO_FILE}' created" "success"
    else
        msg "Info file '${LOCAL_INFO_FILE}' already exists" "warning"
    fi
    
    msg "Creating archive file '${LOCAL_ARCHIVE_FILE}'..."
    
    local args="cvf"
    if [[ $VERBOSE = true ]]; then
        args="cvzf"
    fi

    if [[ ! -f ${LOCAL_ARCHIVE_FILE} ]]; then
        if ! tar $args "${LOCAL_ARCHIVE_FILE}" * >> "$LOGFILE" 2>&1; then
            abord "Error while creating archive file '${LOCAL_ARCHIVE_FILE}'"
        fi

        if ! gzip -t "${LOCAL_ARCHIVE_FILE}"; then
            abord "Error while creating archive file ${LOCAL_ARCHIVE_FILE}. The compressed file is corrupted !"
        fi
        msg "Archive file '${LOCAL_ARCHIVE_FILE}' created !" "success"
    else
        msg "Archive file '${LOCAL_ARCHIVE_FILE}' already exists" "warning"
    fi
    
    archiveSize=$(du -sb "${LOCAL_ARCHIVE_FILE}" | awk "{ print \$1 }")

    msg "Archive file size = ${archiveSize} bytes"
}

# Get available disk space in bytes in rclone remote
function rcloneGetAvalaibleDiskSpace() {
    local _rcloneDiskUsedInBytes=$(rclone size pcloud-crypt: | awk "{ if (\$2 == \"size:\") { print substr(\$5,2) } }")
    echo $(expr $REMOTE_SIZE - $_rcloneDiskUsedInBytes)
}

function rcloneCopy() {
    # Check if there is enough space on remote to tranfert archive and trying to make room
    local _rcloneAvailableSpace=$(rcloneGetAvalaibleDiskSpace)
    local verboseOption=""
    if [[ $VERBOSE = true ]]; then
        verboseOption="-v"
    fi

    if [[ $_rcloneAvailableSpace -lt $archiveSize ]]; then
        msg "There is not enough space on remote to transfert archive file (space left = ${_rcloneAvailableSpace} bytes). Trying to free space on remote..." "warning"

        if ! rclone delete $verboseOption "${RCLONE_DEST}" --min-age 1M --min-size ${archiveSize}B >> "$LOGFILE" 2>&1; then
            msg "Can't make room on remote" "warning"
        fi
    fi

    _rcloneAvailableSpace=$(rcloneGetAvalaibleDiskSpace)
    if [[ $_rcloneAvailableSpace -lt $archiveSize ]]; then
        abord "Can't make enough room on remote. (space left = ${_rcloneAvailableSpace} bytes after trying to delete old archive). Abording"
    fi

    msg "Copy files on remote..."
    if ! rclone copy $verboseOption "$LOCAL_INFO_FILE" "${RCLONE_DEST}" >> "$LOGFILE" 2>&1 || ! rclone copy $verboseOption "$LOCAL_ARCHIVE_FILE" "${RCLONE_DEST}" >> "$LOGFILE" 2>&1; then
        abord "Error while copying files on remote"
    fi
    msg "Files copied on remote !" "success"
}

# Get available disk space in bytes for a submitted directory
# @param $1 string path to test
function getAvalaibleDiskSpace() {
    local _path="$1"

    if [[ ! -e $_path ]]; then
        abord "getAvalaibleDiskSpace path '$_path' provided doesn't exists !"
    fi

    local _mountPoint=$(findmnt -T "$_path" -o SOURCE -n)
    df -B1 --output="source,avail" "$_mountPoint" | awk "{ if (\$1 == \"$_mountPoint\") { print \$2 } }"
}

# Supprime toutes les archives plus anciennes que 3 mois en local et distant
function clean() {
    local _verboseArg=''
    if [[ $VERBOSE = true ]]; then
        _verboseArg='-print'
    fi

    local numberOfDays3MonthAgo=$(( ( $(date '+%s') - $(date -d '3 months ago' '+%s') ) / 86400 ))
    find "$LOCAL_REPO" -mtime +$numberOfDays3MonthAgo -type f -delete $_verboseArg >> "$LOGFILE"
}

# main function for backup to rclone
function main() {
    
    msg "----- Begin backup yunohost to external rclone -----"
    createLocalArchive
    rcloneCopy
    clean

    message="Archive '${LOCAL_ARCHIVE_FILE}' size = ${archiveSize} bytes created and copied on remote '${RCLONE_DEST}' !"
    msg "$message"

    if [[ -n $MAIL && $VERBOSE = true ]]; then
        now="$(date "+%Y-%m-%d %H:%M:%S")"
        echo "$now $message" | mail -s "Yunohost backup rclone - OK" $MAIL
    fi
}

case "$1" in
    need_mount)
        # Set false if your method can itself put files in good place in your archive
        true
        ;;
    backup)
        main
        ;;
    *)
        echo "hook called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0